In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Wine.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

from sklearn.model_selection import train_test_split as tts
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
X_train,X_test,y_train,y_test = tts(X,y,test_size = 0.2, random_state = 0)





from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [101]:
pca = PCA(n_components = 2)

X_train = pca.fit_transform(X_train)
X_test= pca.transform(X_test)
explained_variance = pca.explained_variance_ratio_explained_variance = pca.explained_variance_ratio_
print(X_test)

[[ 3.17929962e+02  1.28454239e+01]
 [-2.62103998e+02  1.61899572e+01]
 [-3.22487166e+02 -7.95816761e+00]
 [ 3.77870540e+02  9.95827714e+00]
 [-3.62517629e+02 -8.29057439e+00]
 [-2.77024951e+02  2.34562656e+01]
 [ 5.52935221e+02  1.21195212e+01]
 [-2.22496420e+02 -8.47961086e+00]
 [-2.32618821e+02 -1.63955327e+01]
 [-2.62600422e+02 -1.49301055e+01]
 [ 3.74826990e+01 -1.16499782e+01]
 [-3.27611470e+02 -1.48424800e+01]
 [ 7.07787765e+02  6.48630004e-01]
 [-8.25025926e+01 -1.07774278e+01]
 [ 7.72862876e+00  4.91944416e+00]
 [-4.64490295e+02 -6.72479909e+00]
 [ 4.93111128e+02  2.40982191e+01]
 [ 9.37689818e+02 -6.97047562e+00]
 [-2.92276622e+02  4.54355617e+00]
 [ 5.22514010e+02 -1.43909380e+01]
 [-2.40619559e+02 -1.83031922e+01]
 [ 3.62590404e+02 -7.85466252e+00]
 [-7.05039313e+00  1.80617400e+01]
 [-7.05702996e+01 -1.39569382e+01]
 [-6.22972468e+01  1.85431792e+00]
 [-4.17476774e+02 -5.44354425e+00]
 [-3.90507741e+02 -7.84795863e+00]
 [-2.47479401e+02 -6.11439087e+00]
 [-1.35272605e+02  5

In [102]:
lr = LogisticRegression(random_state = 0)
lr.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [103]:
y_pred = lr.predict(X_test)

In [104]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
score = accuracy_score(y_test,y_pred)
print(cm)
print(score)


[[13  0  1]
 [ 0 16  0]
 [ 1  4  1]]
0.8333333333333334
